### ISSUE TITLE
Searching in the heroku app throws an error

### ISSUE THREAD

**Issue by sgibson91** [betatim/binder-datasette#1]
Hi, I'm trying to use the app to find some cool examples of binders we support. However, whenever I try the search function, I get a 500 error with the message "database disk image is malformed".

**Comment by betatim** [comment]
A link like https://binderlytics.herokuapp.com/binder-launches/binder?_search=turing&_sort=rowid produces the error you describe. I will try to rebuild the DB and redeploy it to see if that fixes things.

If not ... longer investigating will be needed :)

**Comment by betatim** [comment]
Works again for me. For you as well?

**Comment by sgibson91** [comment]
Yes, thank you! 🚀
